from graphics import *

def main():
    win = GraphWin("Dice", 1200, 200)
    win.setCoords(0, 0, 6, 1)

    die_1 = Rectangle(Point(0, 0), Point(1, 1))
    die_1.setOutline("black")
    die_1.draw(win)
    pip_1 = Circle(Point(0.5, 0.5), 0.05)
    pip_1.setFill("black")
    pip_1.draw(win)

    die_2 = Rectangle(Point(1, 0), Point(2, 1))
    die_2.setOutline("black")
    die_2.draw(win)
    pip_2a = Circle(Point((1 + (1/3)), 0.5), 0.05)
    pip_2a.setFill("black")
    pip_2b = pip_2a.clone()
    pip_2b.move((1/3), 0)
    pip_2a.draw(win)
    pip_2b.draw(win)

    die_3 = Rectangle(Point(2, 0), Point(3, 1))
    die_3.setOutline("black")
    die_3.draw(win)
    pip_3a = Circle(Point(2.25, 0.5), 0.05)
    pip_3a.setFill("black")
    pip_3b = pip_3a.clone()
    pip_3b.move(0.25, 0)
    pip_3c = pip_3a.clone()
    pip_3c.move(0.5, 0)
    pip_3a.draw(win)
    pip_3b.draw(win)
    pip_3c.draw(win)

    die_4 = Rectangle(Point(3, 0), Point(4, 1))
    die_4.setOutline("black")
    die_4.draw(win)
    pip_4a = pip_2a.clone()
    pip_4b = pip_2b.clone()
    pip_4a.move(2, ((1/2)-(1/3)))
    pip_4b.move(2, ((1/2)-(1/3)))
    pip_4c = pip_4a.clone()
    pip_4c.move(0, -(1/3))
    pip_4d = pip_4b.clone()
    pip_4d.move(0, -(1/3))
    pip_4a.draw(win)
    pip_4b.draw(win)
    pip_4c.draw(win)
    pip_4d.draw(win)

    die_5 = Rectangle(Point(4, 0), Point(5, 1))
    die_5.setOutline("black")
    die_5.draw(win)
    pip_5a = pip_4a.clone()
    pip_5b = pip_4b.clone()
    pip_5c = pip_4c.clone()
    pip_5d = pip_4d.clone()
    pip_5a.move(1, 0)
    pip_5b.move(1, 0)
    pip_5c.move(1, 0)
    pip_5d.move(1, 0)
    pip_5a.draw(win)
    pip_5b.draw(win)
    pip_5c.draw(win)
    pip_5d.draw(win)
    pip_5e = pip_3b.clone()
    pip_5e.move(2, 0)
    pip_5e.draw(win)

    die_6 = Rectangle(Point(4, 0), Point(6, 1))
    die_6.setOutline("black")
    die_6.draw(win)
    pip_6a = pip_3a.clone()
    pip_6a.move(3, ((1/2) - (1/3)))
    pip_6a.draw(win)
    pip_6b = pip_3b.clone()
    pip_6b.move(3, ((1/2) - (1/3)))
    pip_6b.draw(win)
    pip_6c = pip_3c.clone()
    pip_6c.move(3, ((1/2) - (1/3)))
    pip_6c.draw(win)
    pip_6d = pip_6a.clone()
    pip_6d.move(0, -(1/3))
    pip_6d.draw(win)
    pip_6e = pip_6b.clone()
    pip_6e.move(0, -(1/3))
    pip_6e.draw(win)
    pip_6f = pip_6c.clone()
    pip_6f.move(0, -(1/3))
    pip_6f.draw(win)

    win.getMouse()
    win.close()


main()